name: Extrair Conteúdo de ESTATICO de download (1).zip

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'download (1).zip'

jobs:
  extract-zip-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Verificar se o arquivo zip existe
        id: check_zip_file
        run: |
          echo "Listando conteúdo da raiz do repositório ANTES da extração:"
          ls -lA .
          echo "---"
          if [ -f "download (1).zip" ]; then
            echo "::set-output name=file_exists::true"
          else
            echo "::set-output name=file_exists::false"
            echo "Arquivo download (1).zip não encontrado na raiz do repositório."
          fi

      - name: Extrair conteúdo do zip (se o arquivo existir)
        if: steps.check_zip_file.outputs.file_exists == 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o "download (1).zip" -d .

          echo "Listando conteúdo da raiz do repositório APÓS a extração inicial:"
          ls -lA .
          echo "---"

          # Verifica se a pasta ESTATICO existe e move seu conteúdo
          if [ -d "ESTATICO" ]; then
            mkdir -p extracted_files
            # **** MUDANÇA AQUI: mv ESTATICO/* para mv ESTATICO/. ****
            # Isso move o *conteúdo* de ESTATICO para extracted_files
            mv ESTATICO/. extracted_files/
            echo "Conteúdo da pasta ESTATICO extraído para extracted_files/"
            echo "Listando conteúdo de extracted_files:"
            ls -R extracted_files/
            echo "---"
          else
            echo "ERRO: Pasta ESTATICO não encontrada dentro do zip após extração."
            exit 1 # Sai com erro
          fi

      - name: Configurar Git para o Commit
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Adicionar, Commitar e Enviar os Arquivos Extraídos
        run: |
          echo "Status do Git antes de adicionar:"
          git status
          echo "---"

          git add extracted_files/

          echo "Status do Git após adicionar:"
          git status
          echo "---"

          if git diff --quiet --exit-code; then
            echo "Não há alterações para commitar."
          else
            echo "Alterações detectadas, commiting..."
            git commit -m "feat: Atualiza arquivos extraídos de download (1).zip [skip ci]"
            echo "Commit realizado. Fazendo push..."
            git push
            echo "Push concluído (ou não)."
          fi
