name: Extrair ESTATICO de download (1).zip

on:
  workflow_dispatch: # Permite acionar o workflow manualmente
  push:
    branches:
      - main # Ou o branch principal do seu repositório (ex: master)
    paths:
      - 'download (1).zip' # Aciona se o arquivo zip for alterado

jobs:
  extract-zip-content:
    runs-on: ubuntu-latest # Usa um runner Ubuntu

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4 # Clona o repositório para o runner

      - name: Verificar se o arquivo zip existe
        id: check_zip_file
        run: |
          if [ -f "download (1).zip" ]; then
            echo "::set-output name=file_exists::true"
          else
            echo "::set-output name=file_exists::false"
            echo "Arquivo download (1).zip não encontrado na raiz do repositório."
          fi

      - name: Extrair conteúdo do zip (se o arquivo existir)
        if: steps.check_zip_file.outputs.file_exists == 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o "download (1).zip" -d . # Extrai para a raiz do workspace

          # Mover o conteúdo de ESTATICO para uma pasta específica para o commit
          if [ -d "ESTATICO" ]; then
            mkdir -p extracted_files # Cria uma pasta para os arquivos que serão versionados
            mv ESTATICO/* extracted_files/ # Move o conteúdo para essa nova pasta
            echo "Conteúdo da pasta ESTATICO extraído para extracted_files/"
            ls -R extracted_files/ # Lista o conteúdo para verificar
          else
            echo "Pasta ESTATICO não encontrada dentro do zip após extração."
            exit 1 # Sai com erro se ESTATICO não for encontrado, para evitar um commit vazio
          fi

      - name: Configurar Git para o Commit
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Adicionar, Commitar e Enviar os Arquivos Extraídos
        run: |
          # Adiciona a pasta com os arquivos extraídos
          git add extracted_files/

          # Verifica se há algo para commitar antes de fazer o commit
          git diff --quiet --exit-code || git commit -m "feat: Adiciona arquivos extraídos de download (1).zip [skip ci]"

          # Faz o push para o branch atual
          # O '[skip ci]' no commit message evita que este push acione um novo workflow,
          # o que poderia criar um loop infinito.
          git push
